### ISSUE TITLE
Error during installation on mac big sur

### ISSUE THREAD

**Issue by farukara** [zegervdv/homebrew-zathura#73]
I started installatin by:

brew install zathura --with-synctex --HEAD

and got following error towards the end:

../zathura/dbus-interface.c:390:20: error: implicit declaration of function 'girara_command_run' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  const bool ret = girara_command_run(zathura->ui.session, input);
                   ^
1 error generated.
[24/44] Compiling C object libzathura.a.p/zathura_file-monitor-glib.c.o
[25/44] Compiling C object libzathura.a.p/zathura_document.c.o
[26/44] Compiling C object libzathura.a.p/zathura_file-monitor-signal.c.o
[27/44] Compiling C object libzathura.a.p/zathura_jumplist.c.o
[28/44] Compiling C object libzathura.a.p/zathura_links.c.o
ninja: build stopped: subcommand failed.

**Comment by zegervdv** [comment]
Did you build girara from head first?

**Comment by VonbatenBach** [comment]
I also have this problem. I tried to build girara from head, and got:

brew install girara --HEAD
==> Installing girara from zegervdv/zathura
==> Cloning https://git.pwmt.org/pwmt/girara.git
Updating /Users/vonbatenbach/Library/Caches/Homebrew/girara--git
==> Checking out branch develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
HEAD is now at b775f24 Remove deprecated 'show-scrollbars', 'show-{h,v}-scrollbar' options
==> mkdir build
==> meson build --prefix /usr/local/Cellar/girara/HEAD-b775f24
==> cd build && ninja && ninja install
Last 15 lines from /Users/vonbatenbach/Library/Logs/Homebrew/girara/03.cd:
[19/19] Linking target libgirara-gtk3.3.dylib
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.57.1/libexec/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.57.1', 'console_scripts', 'meson')())
  File "/usr/local/Cellar/meson/0.57.1/libexec/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: meson
FAILED: meson-install 
/usr/local/Cellar/meson/0.57.1/libexec/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Comment by zegervdv** [comment]
In both cases I would suggest doing a `brew rm girara` and `brew rm zathura` until all versions are removed, then try to install again from scratch.
That second error indicates a missing `meson` package, which is a dependency of both. If nothing else works you can try `brew install meson`.

**Comment by farukara** [comment]
Removing both and reinstalling worked for me. Thanks.
