### ISSUE TITLE
Cannot install zathura on Big Sur 11.5.2

### ISSUE THREAD

**Issue by Stevenchaosz** [zegervdv/homebrew-zathura#80]
The following is the error message
`Last 15 lines from /Users/steven/Library/Logs/Homebrew/girara/03.cd:
[19/19] Linking target libgirara-gtk3.3.dylib
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.59.1/libexec/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.59.1', 'console_scripts', 'meson')())
  File "/usr/local/Cellar/meson/0.59.1/libexec/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: meson
FAILED: meson-install
/usr/local/Cellar/meson/0.59.1/libexec/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issue`

**Comment by zegervdv** [comment]
It seems like an issue with one of the build dependencies: meson. 
Meson is a python tool which is installed in your homebrew’s python environment. I suspect your python version was upgraded and for some reason the meson package was removed or is not in the right location. 
You can see from the trace back that the binary (or rather the entry point) is still there, but the python library cannot be found. 

I suggest trying to brew uninstall meson and try to install zathura again.

**Comment by Stevenchaosz** [comment]
Thanks for your help! But after I tried uninstalling meson, it still shows the same error message. Do I need to work on the ninja part? The last command it runs is the following statement:
`cd build && ninja && ninja install`

**Comment by zegervdv** [comment]
Can you try `brew rm zathura` and `brew rm girara` and repeat until no more versions are found?
Same for `brew rm meson`.
Then try to install again?

**Comment by zegervdv** [comment]
The meson build system made a change without giving deprecation warnings in version 0.60. They reverted that in 0.60.1, which was released 12 hours ago, so once the brew pkg is updated this issue should go away for the time being.

**Comment by zegervdv** [comment]
@ivanddm As far as I can tell the updated meson is available and the builds seem to work

**Comment by hosilva** [comment]
I'm having a similar issue on MacOS 10.15.7. I first uninstalled (doing `brew rm --force`) `girara`, `meson` and `zathura`. Then, I tried to install `zathura` doing:

```
brew tap zegervdv/zathura
brew install zathura --with-synctex
```

and got the following,

```
==> Downloading https://ghcr.io/v2/homebrew/core/meson/manifests/0.61.1
Already downloaded: /Users/hectorokadadasilva/Library/Caches/Homebrew/downloads/e465d55c480cfc0a798372075800d2a9fc6aadb55b808d904d8d1351c3be2426--meson-0.61.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/meson/blobs/sha256:4e7a608cbefd
Already downloaded: /Users/hectorokadadasilva/Library/Caches/Homebrew/downloads/81dc8ae00539af6dc6b11cab5d20ffc8d6ca30e8ccc3660504a25e8bf4c5109a--meson--0.61.1.all.bottle.tar.gz
==> Downloading https://github.com/pwmt/girara/archive/0.3.6.tar.gz
Already downloaded: /Users/hectorokadadasilva/Library/Caches/Homebrew/downloads/2656186a6c3e1cf9379e7e76614194f1d8145e5a06e3102936467116f78efcd1--girara-0.3.6.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/librsvg/manifests/2.52.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/librsvg/blobs/sha256:9c6702f2d5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://github.com/pwmt/zathura/archive/0.4.8.tar.gz
Already downloaded: /Users/hectorokadadasilva/Library/Caches/Homebrew/downloads/03451fbb4a9fd788239c7c1a3554e340750b4953cf39e5fde1bb306cde16fdde--zathura-0.4.8.tar.gz
==> Installing zathura from zegervdv/zathura
==> Installing dependencies for zegervdv/zathura/zathura: meson, girara and librsvg
==> Installing zegervdv/zathura/zathura dependency: meson
==> Pouring meson--0.61.1.all.bottle.tar.gz
🍺  /usr/local/Cellar/meson/0.61.1: 219 files, 3.2MB
==> Installing zegervdv/zathura/zathura dependency: girara
==> mkdir build
==> meson build --prefix /usr/local/Cellar/girara/0.3.6
==> cd build && ninja && ninja install
🍺  /usr/local/Cellar/girara/0.3.6: 42 files, 336.3KB, built in 9 seconds
==> Installing zegervdv/zathura/zathura dependency: librsvg
==> Pouring librsvg--2.52.5.catalina.bottle.tar.gz
==> /usr/local/opt/gdk-pixbuf/bin/gdk-pixbuf-query-loaders --update-cache
🍺  /usr/local/Cellar/librsvg/2.52.5: 53 files, 57.6MB
==> Installing zegervdv/zathura/zathura --with-synctex
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura/0.4.8
Last 15 lines from /Users/hectorokadadasilva/Library/Logs/Homebrew/zathura/02.0.4.8:
Run-time dependency sqlite3 found: YES 3.37.2
Run-time dependency synctex found: YES 1.21.0
Library magic found: YES
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libseccomp found: NO (tried pkgconfig, framework and cmake)
meson.build:93: WARNING: You are using a synctex version pre-SONAME bump, but post-ABI-break. Please make sure to always run zathura using the correct synctex version.
Configuring zathura-version.h using configuration
Found pkg-config: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/usr/local/opt/glib/bin/glib-compile-resources)
Program rsvg-convert found: YES (/usr/local/opt/librsvg/bin/rsvg-convert)

data/meson.build:22:0: ERROR: Function does not take positional arguments.

A full log can be found at /private/tmp/zathura-20220118-56389-1txxpj3/zathura-0.4.8/build/meson-logs/meson-log.txt

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issues

These open issues may also help:
Zathura crashing on segmentation fault https://github.com/zegervdv/homebrew-zathura/issues/47
Cannot install zathura on Big Sur 11.5.2 https://github.com/zegervdv/homebrew-zathura/issues/80
Zathura auto focus on open https://github.com/zegervdv/homebrew-zathura/issues/62
Zathura not recognized by tiling window manager chunkwm. https://github.com/zegervdv/homebrew-zathura/issues/38
Method to run zathura as default pdf viewer https://github.com/zegervdv/homebrew-zathura/issues/78
zathura not showing up on MacOS https://github.com/zegervdv/homebrew-zathura/issues/74
brew install zathura-pdf-mupdf fails https://github.com/zegervdv/homebrew-zathura/issues/66
zathura isn't launched from ViM without --with-synctex https://github.com/zegervdv/homebrew-zathura/issues/50
```

where the critical point seems to be ```data/meson.build:22:0: ERROR: Function does not take positional arguments.```, happening with `meson` version 0.61.1. Does anyone have any suggestions on how to fix this?

**Comment by eli-schwartz** [comment]
> The meson build system made a change without giving deprecation warnings in version 0.60.

This is technically incorrect, no "change" was made.

"ERROR: Function does not take positional arguments." -- these functions have never, ever taken positional arguments, but older versions of meson silently did nothing when given junk data. It is true, that this was downgraded to a warning in meson 0.60.1 because it turned out a lot of projects had broken meson.build which provided junk data to functions, but the warning clearly indicated that only one development cycle of meson would be provided as a grace period.

Meson is constantly improving its support for "catch erroneous junk data provided to functions" and this has never been considered to be a breaking change, even if in one or two cases it has been changed to a warning in the interest of easing adoption.

@hosilva 

> Does anyone have any suggestions on how to fix this?

The fix was committed upstream 2 months ago: https://git.pwmt.org/pwmt/zathura/-/commit/c6ec5044c5ff843979050bfb81742d14740bb656

However I guess it was not tagged in a release.

**Comment by zegervdv** [comment]
@hosilva you can try installing with the `--HEAD` flag to build with the latest changes.

**Comment by hosilva** [comment]
Thanks, @eli-schwartz & @zegervdv: this solved my installation problem.

**Comment by cdaddio** [comment]
Hi all,
i have (it seems) same issue but on Ventura 13.1, i already use --HEAD

`Already` on 'main'
Your branch is up to date with 'origin/main'.
==> Installing dependencies for podman: go, go-md2man, make, glib, gmp, gnu-sed, bdw-gc, libunistring, guile, libidn2, libtasn1, nettle, p11-kit, libevent, libnghttp2, unbound, gnutls, jpeg-turbo, libpng, libslirp, libssh, libusb, lzo, ncurses, pixman, snappy, autoconf, automake, vde, lz4, zstd and qemu
==> Installing podman dependency: go
==> ./make.bash --no-clean
==> /opt/homebrew/Cellar/go/1.19.5/bin/go install -race std
🍺  /opt/homebrew/Cellar/go/1.19.5: 12,458 files, 629.5MB, built in 1 minute 20 seconds
==> Installing podman dependency: go-md2man
==> Pouring go-md2man--2.0.2.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/go-md2man/2.0.2: 6 files, 2MB
==> Installing podman dependency: make
==> ./configure --prefix=/opt/homebrew/Cellar/make/4.4 --program-prefix=g
==> make install
🍺  /opt/homebrew/Cellar/make/4.4: 16 files, 1.2MB, built in 17 seconds
==> Installing podman dependency: glib
==> Patching
==> Applying hardcoded-paths.diff
patching file 'gio/xdgmime/xdgmime.c'
patching file 'glib/gutils.c'
==> meson setup build --default-library=both --localstatedir=/Users/var -Diconv=auto -Dgio_module_dir=/Users/lib/gio/modules -Dbsymbolic_functions=false -Ddtrace=false --prefix=/opt/homebrew/Cellar/glib/2.74.5 --li
Last 15 lines from /Users/cristian/Library/Logs/Homebrew/glib/01.meson:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/opt/meson/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==1.0.0', 'console_scripts', 'meson')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/meson/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for meson

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
 apache-arrow, apache-arrow-glib 11.0.0 https://github.com/Homebrew/homebrew-core/pull/121566
cristian@MacBook-Pro-14-di-Cristian ~ `%`

Thank You

**Comment by iluvcapra** [comment]
I'm having this problem with Sequoia 15.6.

```
$ brew rm --force girara
$ brew install zathura --with-synctex --HEAD
```

Gives me:

```
Last 15 lines from /Users/j/Library/Logs/Homebrew/zathura/01.meson.log:
C linker for the host machine: clang ld64 1221.4
Host machine cpu family: aarch64
Host machine cpu: aarch64
Library m found: YES
WARNING: Found pkg-config '/opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config' but it failed when ran
Found pkg-config: NO
Found CMake: /opt/homebrew/opt/cmake/bin/cmake (4.1.2)
Run-time dependency girara-gtk3 found: NO (tried pkgconfig, framework and cmake)
Not looking for a fallback subproject for the dependency girara-gtk3 because:
Use of fallback dependencies is disabled.

../meson.build:42:9: ERROR: Dependency 'girara-gtk3' is required but not found.

A full log can be found at /private/tmp/zathura-20251024-88148-olg5jb/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

If reporting this issue please do so at (not Homebrew/* repositories):
  https://github.com/homebrew-zathura/homebrew-zathura/issues

These open issues may also help:
Zathura auto focus on open https://github.com/homebrew-zathura/homebrew-zathura/issues/62
Zathura crashing on segmentation fault https://github.com/homebrew-zathura/homebrew-zathura/issues/47
brew install zathura-pdf-mupdf fails https://github.com/homebrew-zathura/homebrew-zathura/issues/66
zathura not showing up on MacOS https://github.com/homebrew-zathura/homebrew-zathura/issues/74
Method to run zathura as default pdf viewer https://github.com/homebrew-zathura/homebrew-zathura/issues/78
Cannot install zathura on Big Sur 11.5.2 https://github.com/homebrew-zathura/homebrew-zathura/issues/80
zathura isn't launched from ViM without --with-synctex https://github.com/homebrew-zathura/homebrew-zathura/issues/50
zathura's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
```
